os: linux
dist: trusty
language: java
jdk:
  - openjdk8
jobs:
  include:
    - stage: test
      script:
        - mvn clean
        - mvn -Dtest.profile=ci -Ptest.coverage -e post-integration-test sonar:sonar
stages:
  - test
addons:
  sonarcloud:
    organization: yassine-github
    token:
      secure: "r0JvS2xCZhY/ynu733XwWGoY/T/JUcFtrxtBxu81PTc2iMjWeZHHkBU/d1giJboQKwko/M8Mz2QazSipqeQE5dQZOlB117w1/viKIDzSU6Wp7dpwhZ1d+RFX3vGE+c4TL1BrcZ+Zcu9Rkm0QzinvkKkHQaME/6UbTNQ835Y9KYWQ6yfLsmdCrofG8VxR21Rx5PZHZz9ToRZL3BBTk0kaiY1cDuBtID1xOti6BrgW3o/lUqtDYKx2zo02m+bfR1nSc011GV+xjOvt4rXlJRZDxzsUhMI4fWMQF8+HkoQogFPC54/x/MaTcpR6RF44lvDzV71a+h9O1UKqs3ISQnVuGo1vgSmRtcoh60MT3pBnFAJQITohIISh2Rdi27HmTtNHORadzsKhwtWCvxN9BBqtY126l4YMTct5e23RgPM9kCzT8i0UDRT/ESrg8U2glKonxbEyqVer0OVJq6YM8435MXxCsyq6NbsikzgH3bzw/vbEpkqpYEOM7RdZGyDGy0Mgk27vbiEyFTFTyWSq0Lo3UKwj1G0aqWFPDrtwpoFC8NRrqpHiCGHXG8W1ATqeiVlbB0PVvLBHeOxrl2RI2nfq7Gq7moiKqo0qUF8ivKay7v31dGwTXgmOnubQiH8rfUZjt5RrQyAYoCVuMf6VbjG09+sZLO/2/PcFrDKL5IooM4o="
notifications:
  email: false
